language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
os: linux
deploy:
  skip_cleanup: true
  provider: pages
  cleanup: false
  local_dir: build
  token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  target-branch: master
  on:
    branch: dev
